[package]
name = "gleiphird"
version = "0.1.0"
authors = ["iovxw <iovxw@outlook.com>"]
edition = '2018'

[dependencies]
libc = "0.2"
nfqueue = { version = "0.9", path = "./nfqueue-rs" }
pnet = "0.21"
pnet_macros_support = "0.21"
pnetlink = "0.0.3"
lazy_static = "1.0"
treebitmap = "0.3"
lru_time_cache = "0.9"
dbus = "0.6"
nix = "0.13"
tarpc = "0.18"
rpc = { package = "tarpc-lib", version = "0.6" }
futures-preview = { version = "0.3.0-alpha.16", features = ["compat"] }

[build-dependencies]
dbus-codegen = "0.3"
