[package]
name = "gleipnird"
version = "0.1.0"
authors = ["iovxw <iovxw@outlook.com>"]
edition = '2018'

[dependencies]
jemallocator = "0.3"
failure = "0.1"
libc = "0.2"
nfqueue = { version = "0.9", path = "./nfqueue-rs" }
pnet = "0.21"
pnet_macros_support = "0.21"
pnetlink = "0.0.3"
lazy_static = "1.0"
treebitmap = "0.3"
lru_time_cache = "0.9"
dbus = "0.6"
nix = "0.13"
tarpc = { version = "0.18",  features = ["serde1"] }
rpc = { package = "tarpc-lib", version = "0.6" }
bincode-transport = { package = "tarpc-bincode-transport", version = "0.7" }
futures-preview = { version = "0.3.0-alpha.16", features = ["compat"] }
futures-locks = "0.3"
tokio = "0.1"
tokio-threadpool = "0.1"
async-bincode = "0.4"
pin-utils = "0.1.0-alpha.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
crossbeam-channel = "0.3"
slab = "0.4"
gleipnir-interface = { version = "0.1", path = "../gleipnir-interface" }

[build-dependencies]
dbus-codegen = "0.3"
