version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  versioning-strategy: lockfile-only
  ignore:
  - dependency-name: libc
    versions:
    - 0.2.82
    - 0.2.84
    - 0.2.85
    - 0.2.86
    - 0.2.88
    - 0.2.90
    - 0.2.91
    - 0.2.92
  - dependency-name: regex
    versions:
    - 1.4.3
    - 1.4.5
  - dependency-name: futures
    versions:
    - 0.3.12
    - 0.3.13
